name: Deploy Dev

on:
  workflow_dispatch: # apenas manual

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Run DB migrations
      run: |
        psql ${{ secrets.DB_DEV_URL }} -f migrations/01.sql
        psql ${{ secrets.DB_DEV_URL }} -f migrations/02.sql
        psql ${{ secrets.DB_DEV_URL }} -f migrations/03.sql

    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-project-id: ${{ secrets.VERCEL_DEV_PROJECT }}
        vercel-org-id: ${{ secrets.VERCEL_ORG }}
        working-directory: ./public
